version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: course_management
    ports:
      - 5432:5432

  app:
    build: .
    image: course-management:0.0.1-SNAPSHOT
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/course_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - 8080:8080
    depends_on:
      - db
